import Head from "next/head";
import Link from "next/link";
import { Navbar } from "../Navbar";

import styles from "../styles/Home.module.css";

export default function about() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ferPM.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Ir a <Link href="/">home!</Link>
        </h1>
      </main>
    </div>
  );
}
