import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../components/UI/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>ferPM.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["grid1"]}>
        <div className={styles["grid-left"]}>
          <div className={styles["img-cv"]}>
            <img src="./fotoCV.jpg" alt="" />
          </div>
          <Navbar />
        </div>
        <div className={styles["grid-midle"]}>
          <div className={styles["flexh5"]}>
            <h5>1</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>2</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>3</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>4</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>5</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>6</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>7</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>8</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>9</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>11</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>12</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>13</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>14</h5>
          </div>
        </div>

        <div className={styles["grid-rigth"]}>
          <p className={styles["text-intro"]}>
            Hello, I'm Fernando Pioli Martínez and make web and mobile
            development. My past as a graphic designer makes me very attentive
            to the requirements of the design area. I see design and programming
            as valuable tools that associated, help to change the world.
          </p>
        </div>
      </div>
      <div className={styles["pinceladas"]}>
        <img src="./pinceladas.png" alt="" />
      </div>
    </>
  );
}
