import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "./styles.module.css";
import { Navbar } from "../UI/Navbar/index";
import { Children } from "react";

export default function MainLayout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ferPM.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["grid1"]}>
        {/*///////////////// ASIDE ////////////////////*/}
        <div className={styles["grid-left"]}>
          <div className={styles["img-cv"]}>
            <img src="./fotoCV.jpg" alt="" />
          </div>
          <Navbar />
        </div>
        <div className={styles["grid-midle"]}>
          <div className={styles["flexh5"]}>
            <h5>1</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>2</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>3</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>4</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>5</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>6</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>7</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>8</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>9</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>11</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>12</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>13</h5>
          </div>
          <div className={styles["flexh5"]}>
            <h5>14</h5>
          </div>
        </div>

        {/*//////////////////// MAIN ///////////////////////*/}
        <div className={styles["grid-rigth"]}>{children}</div>
      </div>
      {/*///////////////// BACKGROUND ////////////////////*/}
      <div className={styles["pinceladas"]}>
        <img src="./pinceladas.png" alt="" />
      </div>
    </div>
  );
}
